spring.application.name=backend
server.port=8081
realsoftware.api.url=https://api.gestionreal.com.ar/index.php
realsoftware.api.cuit=20146251561
realsoftware.api.secret=DE@MBRO@2025

spring.datasource.url=jdbc:postgresql://187.77.37.154:5432/velonet_dashboard
spring.datasource.username=velonet_user
spring.datasource.password=velodato
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
